"""Added timestamp in column of TabGroup table to see when tab groups are created.

Revision ID: e6506e0ff0dc
Revises: 
Create Date: 2022-01-20 21:18:28.993195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6506e0ff0dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabGroup', sa.Column('timeTabGroupCreated', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tabGroup', 'timeTabGroupCreated')
    # ### end Alembic commands ###
